config/routes.rb
Rails.application.routes.draw do
  get '/' => 'pages#map'
  root :to => 'pages#map'
  resources :sites

  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy', as: :log_out

  resources :admins, only: [] do
    resources :posts, except: [:index]
  end
  get '/posts' => 'posts#index'

  resources :links
  resources :volunteer_sites
  get "/real-world" => "volunteer_sites#index"

  get "/about" => "pages#about"
  get "/volunteer" => "pages#volunteer"
  get '/admin' => 'pages#admin'
  get '/updates' => 'pages#updates'

  get '/submit_sites' => "submit_sites#new"
  post '/submit_sites' => "submit_sites#create"
  delete '/submit_sites/:id' => "submit_sites#destroy"
  get '/edit_sites' => "edit_sites#new"
  post '/edit_sites' => "edit_sites#create"
  delete '/edit_sites/:id' => "edit_sites#destroy"
end

app/views/pages/about.html.erb
<div class="container">
  <%= image_tag("handshake.jpg", alt: "Two men shaking hands at the Portland Waterfront ", class: "content-image") %>
  <h1>About Portland ESL Network</h1>
  <div class="content-bg">
    <p>The Portland ESL Network is an organization dedicated to sharing information about ESL classes and resources in the Portland Metro area. We hope that students, teachers, and volunteers can find classes in their neighborhoods.</p>
    <p>Questions? Feel free to <a href="mailto:heidi.dryden@gmail.com" target="_top">contact us</a>!</p>
    <div class="fb-like" data-href="https://www.facebook.com/PortlandEsl/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
  </div>
</div>

app/views/pages/admin.html.erb
<h1>Welcome, <%= current_admin.username %>!</h1>
<div style="margin:auto;max-width:852px;">
    <%= link_to 'Add a New Link', new_link_path, {class: 'btn btn-primary admin', style: "margin-right: 10px;"} %>
    <%= link_to 'Add a New Volunteer Site', new_volunteer_site_path, {class: 'btn btn-primary admin', style: "margin-right: 10px;"} %>
    <%= link_to 'Add a New Class', new_site_path, {class: "btn btn-primary admin", style: "margin-right: 10px;"}  %>
    <%= link_to 'Add a New Blog Post', posts_path, {class: "btn btn-primary admin", style: "margin-right: 10px;"}  %>
    <%= link_to 'Log out', log_out_path, class: 'btn btn-danger admin' %>
  </div>
  <div class="content-bg" style="margin-top:20px;max-width:855px;">
    <h2>Recent Site Submission Requests</h2>
      <% @submit_sites.each do |site| %>
        <h3>Site submitted by: <%= site.user_name %></h3>
        <p>On: <%= site.created_at.strftime('%B %d, %Y') %></p>
        <p>Email: <%= site.user_email %></p>
        <p>Site Name: <%= site.site_name %></p>
        <p>Address: <%= site.site_address %></p>
        <p>Contact information: <%= site.site_contact %></p>
        <p>URL: <%= site.site_url %></p>
        <p>Description: <%= simple_format(site.site_description) %></p>
        <%= link_to "submit_sites/#{site.id}", class: "btn btn-primary", id: "delete-site-request", data: {confirm: "Are you sure you'd like to delete this site request?", method: "delete"} do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
      <% end %>
      <br>
      <%= paginate @submit_sites, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-small pagination-centered' %>
  </div>
  <div class="content-bg" style="margin-top:20px;max-width:855px;">
    <h2>Recent Site Update Requests</h2>
      <% @edit_sites.each do |edit_site| %>
        <h3>Site submitted by: <%= edit_site.user_name %></h3>
        <p>On: <%= edit_site.created_at.strftime('%B %d, %Y') %></p>
        <p>Site to Update: <%= edit_site.site.try(:name) %></p>
        <p>Site Region: <%= edit_site.site.try(:region) %></p>
        <p>Email: <%= edit_site.user_email %></p>
        <p>Updates: <%= simple_format(edit_site.site_updates) %></p>
        <%= link_to "edit_sites/#{edit_site.id}", class: "btn btn-primary", id: "delete-edit-site", data: {confirm: "Are you sure you'd like to delete this update request?", method: "delete"} do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
      <% end %>
      <br>
      <%= paginate @edit_sites, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-small pagination-centered' %>
  </div>

app/views/pages/map.html.erb
<a href="https://portlandesl.wixsite.com/wixsite/blog" target="_blank"><div class="banner-announcement">
  View our blog for COVID-19 class update information
</div></a>
<div class="search-nav">
  <%= form_tag root_path, method: 'get', role: 'search' do %>
    <%= label_tag :center, 'Find a Class Near You:' %>
    <%= text_field_tag :center, params[:center], placeholder: 'Enter Zip Code', class: 'form-control', id: 'center-map' %>
    <%= submit_tag 'Search', name: nil, class: 'btn btn-primary' %>
  <% end %>
  <% if @center %>
  <p> Your search: <%= @center %></p>
  <% end %>
</div>


<div id="map-container">
  <div id="map"></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.map.centerOn(<%= @center_on %>);
    handler.getMap().setZoom(<%= @zoom %>);
  });
</script>

app/views/pages/updates.erb
<div class="container">
  <h1>COVID-19 Updates</h1>
  <div class="content-bg">
    <p>Portland ESL Network will be updating our blog with any new information we receive about class changes due to COVID-19. Please contact class organizers for specific information about closures, delays, and online learning.</p>
    <p>Check out our blog updates here: <a href="https://portlandesl.wixsite.com/wixsite/blog" target="_blank">Portland ESL Network Blog</a></p>
  </div>
</div>

app/views/pages/volunteer.html.erb
<div class="container">
  <%= image_tag("river.JPG", alt: "Two women smiling and standing at a viewpoint of the Columbia River", class: "content-image") %>
  <h1>Volunteer with Portland ESL Network</h1>
  <div class="content-bg">
    <p>The Portland ESL Network is looking for volunteer interns! We are seeking the following positions. Please <a href="mailto:heidi.dryden@gmail.com" target="_top">contact us</a> if you are interested!</p>
    <h3>Quarterly Updater</h3>
    <p>Join the Portland ESL Network team to update a section of the website at the beginning of each quarter.</p>
    <ul class="bullets">
      <li>Contact each ESL class and verify and update the class information</li>
      <li>Make appropriate updates to the network’s database</li>
      <li>Test links to make sure they are still active</li>
      <li>Search for new classes in your assigned area of the city (ie. North Portland, Gresham, etc)</li>
      <li>Post any new classes or changes to FB as necessary</li>
      <li>Attend a quarterly Portland ESL Network meeting </li>
      <li>When appropriate help promote the website (ie. manage a Portland ESL Network table at resource fair, hand out brochures)</li>
    </ul>
    <h3>News Publisher/Networker</h3>
    <p>We need a publisher to help with publicity helping people who need to find ESL classes and resources will learn about the Portland ESL Network service.</p>
    <ul class="bullets">
      <li>Email articles regarding the latest Portland ESL Network happenings to community newsletters, email list serves, school for school newsletters, newspapers, online forums and calendars, etc.</li>
      <li>Research social service newsletters and list serves and send email with a paragraph explaining the Portland ESL Network to social services (Goal of 10 list serves reaching at least 25 people each)</li>
      <li>Post Portland ESL Network volunteer opportunities on FB and CNRG and Appling</li>
      <li>Network to help find new class information to add to the class list database</li>
      <li>Post weekly news/tips/esl resources to FB</li>
    </ul>
  </div>
</div>