config/routes.rb
Rails.application.routes.draw do
  get '/' => 'pages#map'
  root :to => 'pages#map'
  resources :sites

  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy', as: :log_out

  resources :admins, only: [] do
    resources :posts, except: [:index]
  end
  get '/posts' => 'posts#index'

  resources :links
  resources :volunteer_sites
  get "/real-world" => "volunteer_sites#index"

  get "/about" => "pages#about"
  get "/volunteer" => "pages#volunteer"
  get '/admin' => 'pages#admin'
  get '/updates' => 'pages#updates'

  get '/submit_sites' => "submit_sites#new"
  post '/submit_sites' => "submit_sites#create"
  delete '/submit_sites/:id' => "submit_sites#destroy"
  get '/edit_sites' => "edit_sites#new"
  post '/edit_sites' => "edit_sites#create"
  delete '/edit_sites/:id' => "edit_sites#destroy"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :admin
  paginates_per 5
  validates :title, :content, presence: true
  validates :title, length: { maximum: 200 }
  validates :content, length: { maximum: 1000 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC').page(params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @admin = Admin.find(params[:admin_id])
    @post = @admin.posts.new(post_params)
    if @post.save
      flash[:notice] = "You have successfully created your blog post!"
      respond_to do |format|
        format.html { redirect_to posts_path }
        format.js
      end
    else
      flash[:alert] = "Sorry, your post has not been successfully created."
      render :new
    end
  end

  def edit
    @admin = Admin.find(params[:admin_id])
    @post = Post.find(params[:id])
  end

  def update
    @admin = Admin.find(params[:admin_id])
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "You have successfully submitted your edits for this post."
      respond_to do |format|
        format.html { redirect_to posts_path }
        format.js
      end
    else
      flash[:alert] = "Sorry, your post updates have not been successfully processed."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "You have successfully deleted this post."
      redirect_to posts_path
    else
      flash[:alert] = "There was a problem. Your post has not been deleted."
      redirect_to posts_path
    end
  end

private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/views/posts/_form.html.erb
<%= render "layouts/errors", object: @post %>

<%= form_for [current_admin, @post], remote: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
  <%= f.label :content %>
  <%= f.text_area :content, class: "form-control" %>
  <%= f.submit 'Submit Post', class: "btn btn-primary" %>
  <%= link_to 'Cancel', '#', class: "btn btn-primary", id: "cancel-edit-post" %>
<% end %>

<script>
$('cancel-edit-post').click(function(){
  $('#edit_post_link_<%=@post.id%>').show();
  $('#edit_post_<%=@post.id%>').remove();
});
</script>

app/views/posts/_post.html.erb
<h3><%= post.title %></h3>
<h6>Posted <%= post.created_at.strftime('%B %d, %Y') %></h6>
<article role="article">
  <p><%= simple_format(post.content) %></p>
</article>
<% if is_author(post) %>
  <span id="edit_post_link_<%=post.id%>">
    <%= link_to edit_admin_post_path(current_admin, post), class: "btn btn-primary", id: 'edit-post', remote: true do %>
      <i class="glyphicon glyphicon-pencil"></i>
    <% end %>
  </span>
  <%= link_to admin_post_path(current_admin, post), class: "btn btn-primary", id: 'delete-post', data: {confirm: "Are you sure you'd like to delete this post?", method: "delete"} do %>
    <i class="glyphicon glyphicon-trash"></i>
  <% end %>
<% end %>
<hr>

app/views/posts/create.js.erb
$('#new-post-link').show();
$('#new_post').remove();
$('#posts-display').prepend("<%= j render partial: 'post', locals: { post: @post } %>");

app/views/posts/edit.html.erb
<h1>Edit this Post</h1>

<%= render 'form' %>

app/views/posts/edit.js.erb
$('#edit_post_link_<%=@post.id%>').hide().after('<%= j render "form" %>')

app/views/posts/index.html.erb
<h1>Portland ESL Network Community News</h1>
<div class="content-bg">
  <% if current_admin %>
  <%= link_to 'Add a New Post', new_admin_post_path(current_admin), id: 'new-post-link', class: "btn btn-primary", remote: true  %>
  <% end %>
  <ul id="posts-display">
    <% @posts.each do |post| %>
    <li id="post-display-<%=post.id%>"><%= render partial: 'post', locals: { post: post } %></li>
    <% end %>
  </ul>
  <%= paginate @posts, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-small pagination-centered' %>
</div>

app/views/posts/new.html.erb
<h3>New Blog Post by <%= current_admin.username %></h3>

<%= render 'form' %>

app/views/posts/new.js.erb
$('#new-post-link').hide().after('<%= j render "form" %>');

$('cancel-edit-post').click(function(){
  $('#new-post-link').show();
  $('#new_post').remove();
});

app/views/posts/update.js.erb
$('#edit_post_link_<%=@post.id%>').show();
$('#edit_post_<%=@post.id%>').remove();
$('#post-display-<%=@post.id%>').html("<%= j render partial: 'post', locals: {post: @post} %>");