config/routes.rb
Rails.application.routes.draw do
  get '/' => 'pages#map'
  root :to => 'pages#map'
  resources :sites

  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy', as: :log_out

  resources :admins, only: [] do
    resources :posts, except: [:index]
  end
  get '/posts' => 'posts#index'

  resources :links
  resources :volunteer_sites
  get "/real-world" => "volunteer_sites#index"

  get "/about" => "pages#about"
  get "/volunteer" => "pages#volunteer"
  get '/admin' => 'pages#admin'
  get '/updates' => 'pages#updates'

  get '/submit_sites' => "submit_sites#new"
  post '/submit_sites' => "submit_sites#create"
  delete '/submit_sites/:id' => "submit_sites#destroy"
  get '/edit_sites' => "edit_sites#new"
  post '/edit_sites' => "edit_sites#create"
  delete '/edit_sites/:id' => "edit_sites#destroy"
end

app/models/site.rb
class Site < ActiveRecord::Base

  validates :name, :address, :city, :state, :region, presence: true
  validates :name, :address, :contact, :email, :url, length: { maximum: 200 }
  validates :city, length: { maximum: 30 }
  validates :state, length: { maximum: 2 }
  validates :zip, length: { maximum: 5 }
  validates :description, length: { maximum: 3000 }
  validates :phone, length: { maximum: 25 }
  validates :notes, length: { maximum: 2000 }

  paginates_per 10

  # Set Marker Colors
  # before_save :set_marker_color , if: ->(obj){ obj.site_type.present? and obj.site_type_changed? }

  # def set_marker_color
  #   if self.site_type === 'Church'
  #     self.markers_url = 'http://maps.google.com/mapfiles/kml/paddle/red-circle.png'
  #   elsif self.site_type === 'Community College or University'
  #     self.markers_url = 'http://maps.google.com/mapfiles/kml/paddle/blu-circle.png'
  #   elsif self.site_type === 'For-Profit Business'
  #     self.markers_url = 'http://maps.google.com/mapfiles/kml/paddle/purple-circle.png'
  #   elsif self.site_type === 'Library'
  #     self.markers_url = 'http://maps.google.com/mapfiles/kml/paddle/ylw-circle.png'
  #   elsif self.site_type === 'Public School'
  #     self.markers_url = 'http://maps.google.com/mapfiles/kml/paddle/ltblu-circle.png'
  #   elsif self.site_type === 'Social Service/Government/Non-Profit'
  #     self.markers_url = 'http://maps.google.com/mapfiles/kml/paddle/grn-circle.png'
  #   else
  #     self.markers_url = 'http://maps.google.com/mapfiles/kml/paddle/wht-circle.png'
  #   end
  # end

# Set In Session Scopes
  scope(:in_session, -> do
    where({happening_now: "Yes"})
  end)
  scope(:not_in_session, -> do
    where("happening_now=? OR happening_now=? OR happening_now=?", "No", "Don't Know", "")
  end)

# Set Region Scopes
  scope(:north_northeast, -> do
    where({region: "North/Northeast"})
  end)

  scope(:south_southeast, -> do
    where({region: "South/Southeast"})
  end)

  scope(:southwest, -> do
    where({region: "Southwest"})
  end)

  scope(:downtown, -> do
    where({region: "Downtown"})
  end)

  scope(:gresham, -> do
    where({region: "Gresham"})
  end)

  scope(:washington_county, -> do
    where({region: "Washington County"})
  end)

  scope(:clark_county, -> do
    where({region: "Clark County"})
  end)

  scope(:other_areas, -> do
    where({region: "Other Areas"})
  end)

  def self.searchable_columns
    [:name, :region, :city, :address, :zip, :state]
  end

  #For Geocoder Functionality
  geocoded_by :geocoder_address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? or obj.city_changed? or obj.state_changed? or obj.zip_changed? }
  after_validation :lat_changed?

  def geocoder_address
    [address, city, state, zip].compact.join(', ')
  end

  def lat_changed?
    if (self.address_changed?) or (self.city_changed?) or (self.zip_changed?)
        if !(self.latitude_changed?)
            self.errors.add(:address, "is not valid.")
            return false
        end
      end
    return true
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :is_admin, only:[:new, :edit, :destroy]

  def index
    # Sort Sites by Region
    if params[:region].present?
      if params[:region] == 'north-northeast'
        @selected_search = 'North/Northeast'
        if current_admin
          @sites = Site.north_northeast.order('name ASC').page(params[:page])
        else
          @sites = Site.north_northeast.where(happening_now: 'Yes').order('name ASC').page(params[:page])
        end
      elsif params[:region] == 'south-southeast'
        @selected_search = 'South/Southeast'
        if current_admin
          @sites = Site.south_southeast.order('name ASC').page(params[:page])
        else
          @sites = Site.south_southeast.where(happening_now: 'Yes').order('name ASC').page(params[:page])
        end
      elsif params[:region] == 'southwest'
        @selected_search = 'Southwest'
        if current_admin
          @sites = Site.southwest.order('name ASC').page(params[:page])
        else
          @sites = Site.southwest.where(happening_now: 'Yes').order('name ASC').page(params[:page])
        end
      elsif params[:region] == 'downtown'
        @selected_search = 'Downtown'
        if current_admin
          @sites = Site.downtown.order('name ASC').page(params[:page])
        else
          @sites = Site.downtown.where(happening_now: 'Yes').order('name ASC').page(params[:page])
        end
      elsif params[:region] == 'gresham'
        @selected_search = 'Gresham'
        if current_admin
          @sites = Site.gresham.order('name ASC').page(params[:page])
        else
          @sites = Site.gresham.where(happening_now: 'Yes').order('name ASC').page(params[:page])
        end
      elsif params[:region] == 'washington-county'
        @selected_search = 'Washington County'
        if current_admin
          @sites = Site.washington_county.order('name ASC').page(params[:page])
        else
          @sites = Site.washington_county.where(happening_now: 'Yes').order('name ASC').page(params[:page])
        end
      elsif params[:region] == 'clark-county'
        @selected_search = 'Clark County'
        if current_admin
          @sites = Site.clark_county.order('name ASC').page(params[:page])
        else
          @sites = Site.clark_county.where(happening_now: 'Yes').order('name ASC').page(params[:page])
        end
      elsif params[:region] == 'other-areas'
        @selected_search = 'Other Areas'
        if current_admin
          @sites = Site.other_areas.order('name ASC').page(params[:page])
        else
          @sites = Site.other_areas.where(happening_now: 'Yes').order('name ASC').page(params[:page])
        end
      end
      
    # Sort Sites by In Session
    elsif params[:happening].present?
      @selected_search = 'Choose a Region'
      if params[:happening] == 'in-session'
        @sites = Site.in_session.order('name ASC').page(params[:page])
      elsif params[:happening] == 'not-in-session'
        @sites = Site.not_in_session.order('name ASC').page(params[:page])
      end
    elsif params[:volunteers_needed].present?
      @selected_search = 'Choose a Region'
      @sites = Site.where(volunteers_needed: true).order('name ASC').page(params[:page])
    else
      @selected_search = 'Choose a Region'
      if current_admin
        @sites = Site.all.order('name ASC').page(params[:page])
      else
        @sites = Site.where(happening_now: 'Yes').order('name ASC').page(params[:page])
      end
    end

    if params[:site].present?
      if current_admin
        @sites = Site.all.fuzzy_search(name: params[:site]).page(params[:page])
      else
        @sites = Site.where(happening_now: 'Yes').fuzzy_search(name: params[:site]).page(params[:page])
      end
    end
  end

  def show
    @site = Site.find(params[:id])
    regions_dict = {
                    'North/Northeast':'north-northeast', 
                    'South/Southeast':'south-southeast', 
                    'Southwest':'southwest',
                    'Downtown':'downtown',
                    'Gresham':'gresham',
                    'Washington County':'washington-county',
                    'Clark County':'clark-county',
                    'Other Areas':'other-areas'
                  }.stringify_keys

    @region_link = regions_dict[@site.region]

    #Init Gmaps
    @hash = Gmaps4rails.build_markers(@site) do |site, marker|
      if site.url != ""
        marker.infowindow "<b>" +
        "<a href='#{site.url}' target='_blank'>" +
         "#{site.name}</a></b><p>#{site.address} #{site.city}, #{site.state} #{site.zip}<br>#{site.phone}</p>"
      else
        marker.infowindow "<b>#{site.name}</b><p>#{site.address} #{site.city}, #{site.state} #{site.zip}<br>#{site.phone}</p>"
      end
      marker.lat site.latitude
      marker.lng site.longitude
    end
    @center_on = [@site.latitude, @site.longitude]
    @zoom = 13
  end

  def new
    @site = Site.new
  end

  def create
    @site = Site.new(site_params)
    if @site.save
      # ClassUpdateMailer.class_created(@site).deliver!
      flash[:notice] = "You have successfully submitted a class!"
      redirect_to sites_path
    else
      flash[:alert] = "Sorry, your class has not been successfully submitted."
      render :new
    end
  end

  def edit
    @site = Site.find(params[:id])
  end

  def update
    @site = Site.find(params[:id])
    if @site.update(site_params)
      # ClassUpdateMailer.class_updated(@site).deliver!
      flash[:notice] = "You have successfully submitted your updates for this class."
      redirect_to site_path(@site)
    else
      flash[:alert] = "Sorry, your class updates have not been successfully submitted."
      render :edit
    end
  end

  def destroy
    @site = Site.find(params[:id])
    if @site.destroy
      flash[:notice] = "You have successfully deleted this class."
      redirect_to sites_path
    else
      flash[:alert] = "There was a problem. The class has not been deleted."
      redirect_to sites_path
    end
  end

private
  def site_params
    params.require(:site).permit(:name, 
                                 :region, 
                                 :address, 
                                 :city, 
                                 :state, 
                                 :zip, 
                                 :contact, 
                                 :phone, 
                                 :email, 
                                 :url, 
                                 :class_resource,
                                 :site_type,
                                 {:class_type => []},
                                 :class_format, 
                                 :description, 
                                 :happening_now, 
                                 :summer_classes, 
                                 :students_served, 
                                 :notes, 
                                 :volunteers_needed, 
                                 :vol_coordinator_name, 
                                 :vol_contact, 
                                 :vol_time_commitment, 
                                 :vol_time_slots, 
                                 :vol_assignment_type, 
                                 :vol_training_offered,
                                 {:days_offered => []},
                                 {:time_of_day => []},
                                 :childcare,
                                 :registration_required,
                                 {:level => []},
                                 {:cost => []},
                                 :organization)
  end
end

app/views/sites/edit.html.erb
<h1>Edit this Class Information</h1>

<div class="content-bg">
	<%= render 'form' %>
</div>

app/views/sites/index.html.erb
<div style="max-width: 1080px; margin: auto;">
  
  <div class="form-inline">
    <%= form_tag sites_path, method: 'get', role: 'search' do %>
      <%= text_field_tag :site, params[:site], class: 'form-control eighty', id: 'site-search' %>
      <%= submit_tag 'Search Classes', name: nil, :class => params[:site] ? 'btn btn-success' : 'btn btn-primary' %>
    <% end %>  
  </div>
  <div class="dropdown">
    <% if params[:region]%>
      <button class="dropdown-toggle btn btn-success" type="button" data-toggle="dropdown"><%= @selected_search %>
      <span class="caret"></span></button>
    <% else %>
      <button class="dropdown-toggle btn btn-primary" type="button" data-toggle="dropdown"><%= @selected_search %>
      <span class="caret"></span></button>
    <% end %>
    <ul class="dropdown-menu">
      <li><a href="/sites">All</a></li>
      <li><a href="?region=north-northeast">North/Northeast</a></li>
      <li><a href="?region=south-southeast">South/Southeast</a></li>
      <li><a href="?region=southwest">Southwest</a></li>
      <li><a href="?region=downtown">Downtown</a></li>
      <li><a href="?region=gresham">Gresham</a></li>
      <li><a href="?region=washington-county">Washington County</a></li>
      <li><a href="?region=clark-county">Clark County</a></li>
      <li><a href="?region=other-areas">Other Areas</a></li>
    </ul>
    <%= link_to 'Volunteers Needed', '?volunteers_needed=true', :class => params[:volunteers_needed] ? 'btn btn-success' : 'btn btn-primary' %>
    <% if params!={"controller"=>"sites", "action"=>"index"} %>
    <%= link_to 'See All Classes', sites_path, :class => params=={"controller"=>"sites", "action"=>"index"} ? 'btn btn-success' : 'btn btn-primary' %> 
    <% end %> 
  </div>

</div>
<br>
<!-- <% if current_admin %>
  <div class="btn-group" role="group">
    <a href="?happening=in-session"><button type="button" class="btn btn-primary"><i class="glyphicon glyphicon-ok" style="color:green"></i> In Session</button></a>
    <a href="?happening=not-in-session"><button type="button" class="btn btn-primary"><i class="glyphicon glyphicon-remove" style="color:red"></i> Not in Session</button></a>
    <a href="/sites"><button type="button" class="btn btn-primary">All</button></a>
  </div>
<% end %> -->
<div class="content-bg">
  <% if current_admin %>
    <%= link_to '+ Add a New Class', new_site_path, class: "btn btn-primary right top"  %>
  <% end %>
  <% if !current_admin %>
    <%= link_to '+ Add a New Class', submit_sites_path, class: "btn btn-primary right top"  %>
  <%end%>  
  <% if @sites.length > 0 %>
    <div style="display: inline-block;">
      <i class="fas fa-wifi" style="color:#484842"></i> = Virtual 
    </div>
    <div style="display: inline-block; margin-left: 10px;">
      <i class="fas fa-user" style="color:#484842"></i> = In-Person 
    </div>
    <div style="display: inline-block; margin-left: 10px; margin-bottom: 5px;">
      <i class="fas fa-wifi" style="color:#484842"></i><i class="fas fa-user" style="color:#484842"></i> = Hybrid or Flexible 
    </div>
    <% if current_admin %>
          <% @sites.each do |site| %>
              <div>
              <% if site.happening_now == 'Yes' %>
                <i class="glyphicon glyphicon-ok left" style="color:green"></i>
              <% else %>
                <i class="glyphicon glyphicon-remove left" style="color:red"></i>
              <% end %>
                <% if site.class_format.present? %>
                    <% if site.class_format == 'Virtual' || site.class_format == "Hybrid" || site.class_format == "Flexible" %>
                    <i class="fas fa-wifi left" style="color:#484842"></i> 
                    <% end %>
                    <% if site.class_format == 'In-Person' || site.class_format == "Hybrid" || site.class_format == "Flexible" %>
                    <i class="glyphicon glyphicon-user left" style="color:#484842"></i> 
                    <% end %>                  
                <% end %>         
                <h3 style="margin-top:5px"><%= link_to site.name, site_path(site), class: 'site-link' %></h3>
              </div>

              <p><b>Last Updated: <%= site.updated_at.strftime('%B %d, %Y') %></b></p>

              <p>
                Address: <%= site.address %> <%= site.city %>, <%= site.state %> <%= site.zip %>
              </p>
              <p>
                <% if site.description.present? %>
                <p>Description: <%= truncate(site.description, length: 75, separator: ' ')%> </p>
                <p><%= link_to 'More Details', site_path(site), class: 'site-link' %></p>
                <% else %>
                <p>Description: No description provided yet.</p>
                <p><%= link_to 'More Details', site_path(site), class: 'site-link' %></p>
                <% end %>
              </p>
              <hr>
          <% end %>
        <%= paginate @sites, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-small pagination-centered' %>
    <% else %>
        <% @sites.each do |site| %>
        <div>
        <% if site.class_format.present? %>
            <% if site.class_format == 'Virtual' || site.class_format == "Hybrid" || site.class_format == "Flexible" %>
            <i class="fas fa-wifi left" style="color:#484842"></i> 
            <% end %>
            <% if site.class_format == 'In-Person' || site.class_format == "Hybrid" || site.class_format == "Flexible" %>
            <i class="glyphicon glyphicon-user left" style="color:#484842"></i> 
            <% end %>                  
        <% end %>         
        <h3 style="margin-top: 5px;"><%= link_to site.name, site_path(site), class: 'site-link' %></h3>
        </div>
        

        <p>
          Address: <%= site.address %> <%= site.city %>, <%= site.state %> <%= site.zip %>
        </p>
        <p>
          <% if site.description.present? %>
          <p>Description: <%= truncate(site.description, length: 75, separator: ' ') %></p>
          <p><%= link_to 'More Details', site_path(site), class: 'site-link' %></p>
          <% else %>
          <p>Description: No description provided yet.</p>
          <p><%= link_to 'More Details', site_path(site), class: 'site-link' %></p>
          <% end %>
        </p>
        <hr>
        <% end %>
      <%= paginate @sites, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-small pagination-centered' %>
    <% end %>
  <% else %>
  <p> Sorry, no classes matched your search. </p>
  <% end %>
</div>

app/views/sites/new.html.erb
<h1>Add an ESL Class Site</h1>

<div class="content-bg">
	<%= render 'form' %>
</div>

app/views/sites/show.html.erb
<h1><%= @site.name %></h1>
<div class="content-bg">
  <% if current_admin %>
  <%= link_to edit_site_path(@site), class: "btn btn-primary", id: "edit-site" do %>
  <i class="glyphicon glyphicon-pencil"></i>
  <% end %>
  <%= link_to site_path(@site), class: "btn btn-primary", id: "delete-site", data: {confirm: "Are you sure you'd like to delete this class?", method: "delete"} do %>
  <i class="glyphicon glyphicon-trash"></i>
  <% end %>
  <% end %>
  <h4>Class Information</h4>
  <p>Address:
    <%= link_to "http://www.google.com/maps/search/#{@site.address}#{@site.city}#{@site.state}#{@site.zip}", target:"_blank" do %>
      <%= @site.address %> <%= @site.city %>, <%= @site.state %> <%= @site.zip %>
    <% end %>
  </p>
  <% if @site.url.present? %>
  <p>Website: <%= link_to @site.url, url_with_protocol(@site.url), target: '_blank' %></p>
  <% end %>
  <% if @site.contact.present? %>
  <p>Contact: <%= @site.contact %></p>
  <% end %>
  <% if @site.phone.present? %>
  <p>Phone: <%= tel_to(@site.phone) %></p>
  <% end %>
  <% if @site.email.present? %>
  <p>Email: <%= mail_to(@site.email) %></p>
  <% end %>
  <!-- Class Type -->
  <% if @site.class_type.reject(&:empty?).length > 0 %>
  <p>Class Type(s): <%= @site.class_type.reject(&:empty?).join(", ") %></p>
  <% end %>

  <!-- Class Format -->
  <% if @site.class_format.present? %>
    <p>
      Class Format: <%= @site.class_format %>
    
      <!-- Class Format Icon -->
      <% if @site.class_format == 'Virtual' || @site.class_format == "Hybrid" || @site.class_format == "Flexible" %>
        <i class="fas fa-wifi" style="color:#484842"></i> 
      <% end %>
      <% if @site.class_format == 'In-Person' || @site.class_format == "Hybrid" || @site.class_format == "Flexible" %>
        <i class="glyphicon glyphicon-user" style="color:#484842"></i>
      <% end %>

    </p>
  <% end %>

  <!-- Days -->
  <% if @site.days_offered.reject(&:empty?).length > 0 %>
  <p>Days Offered: <%= @site.days_offered.reject(&:empty?).join(", ") %></p>
  <% end %>
  <!-- Time -->
  <% if @site.time_of_day.reject(&:empty?).length > 0 %>
  <p>Time of Day: <%= @site.time_of_day.reject(&:empty?).join(", ") %></p>
  <% end %>
  <!-- Level -->
  <% if @site.level.reject(&:empty?).length > 0 %>
  <p>Level(s): <%= @site.level.reject(&:empty?).join(", ") %></p>
  <% end %>
  <!-- Cost -->
  <% if @site.cost.reject(&:empty?).length > 0 %>
  <p>Cost: <%= @site.cost.reject(&:empty?).join(", ") %></p>
  <% end %>
  <% if @site.description.present? %>
  <p>Description: <%= simple_format(@site.description) %></p>
  <% else %>
  <p>Description: No description provided yet.</p>
  <% end %>
  <!-- Registration -->
  <% if @site.registration_required.present? %>
  <p>Registration: <%= @site.registration_required %></p>
  <% end %>
  <!-- Childcare -->
  <% if @site.childcare.present? %>
  <p>Childcare: <%= @site.childcare %></p>
  <% end %>

  <p>Last updated: <%= @site.updated_at.strftime('%B %d, %Y') %></p>

  <% if @site.volunteers_needed %>
    <hr>
    <h4>Volunteers Needed!</h4>
    <% if @site.vol_coordinator_name.present? %>
    <p>Volunteer Coordinator: <%= @site.vol_coordinator_name %></p>
    <% end %>
    <% if @site.vol_contact.present? %>
    <p>Volunteer Contact: <%= @site.vol_contact %></p>
    <% end %>
    <% if @site.vol_assignment_type.present? %>
    <p>Type of Assignment: <%= @site.vol_assignment_type %></p>
    <% end %>
    <% if @site.vol_time_slots.present? %>
    <p>Time Slots Needed: <%= @site.vol_time_slots %></p>
    <% end %>
    <% if @site.vol_time_commitment.present? %>
    <p>Time Commitment Requested: <%= @site.vol_time_commitment %></p>
    <% end %>
    <% if @site.vol_training_offered.present? %>
    <p>Training Offered?: <%= @site.vol_training_offered ? 'Yes' : 'No' %></p>
    <% end %>
  <% end %>

  <% if current_admin %>
  <hr>
  <h4>Admin Information</h4>
  <p>Class or Resource: <%= @site.class_resource %></p>
  <p>Site type: <%= @site.site_type %></p>
  <p>Organization: <%= @site.organization %></p>
  <p>Happening now?: <%= @site.happening_now %></p>
  <p>Notes: <%= @site.notes %></p>
  <p>Region: <%= @site.region %></p>
  <p>Summer classes?: <%= @site.summer_classes %></p>
  <p>Students served?: <%= @site.students_served %></p>
  <% end %>

  <% if !current_admin %>
    <%= link_to 'Submit Updates to Class', edit_sites_path(site: @site), {style: "margin-right: 20px;", class: "btn btn-primary"}  %>
  <%end%>

  <%= link_to "Back to #{@site.region}", "/sites?region=#{@region_link}", class: "btn btn-primary"  %>
  <%= link_to 'Back to All Classes', sites_path, class: "btn btn-secondary"  %>
</div>
<div id="site-map-container">
  <div id="site-map"></div>
</div>
<br>
<br>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'site-map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.map.centerOn(<%= @center_on %>);
    handler.getMap().setZoom(<%= @zoom %>);
  });
</script>