config/routes.rb
Rails.application.routes.draw do
  get '/' => 'pages#map'
  root :to => 'pages#map'
  resources :sites

  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy', as: :log_out

  resources :admins, only: [] do
    resources :posts, except: [:index]
  end
  get '/posts' => 'posts#index'

  resources :links
  resources :volunteer_sites
  get "/real-world" => "volunteer_sites#index"

  get "/about" => "pages#about"
  get "/volunteer" => "pages#volunteer"
  get '/admin' => 'pages#admin'
  get '/updates' => 'pages#updates'

  get '/submit_sites' => "submit_sites#new"
  post '/submit_sites' => "submit_sites#create"
  delete '/submit_sites/:id' => "submit_sites#destroy"
  get '/edit_sites' => "edit_sites#new"
  post '/edit_sites' => "edit_sites#create"
  delete '/edit_sites/:id' => "edit_sites#destroy"
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Portland Esl Network</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'logo_small.ico' %>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.google.com/maps/api/js?key=<%=ENV['GOOGLE_API_KEY']%>"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=<%=ENV['GOOGLE_ANALYTICS_ID']%>"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', '<%=ENV['GOOGLE_ANALYTICS_ID']%>');
    </script>
  </head>

  <nav class="navbar navbar-inverse">
    <div class="logo">
      <a href="/"><%= image_tag("header-title.jpg", alt: "Portland ESL Network Logo") %></a>
      <!-- <a href="/"><%= image_tag("header-title.jpg", alt: "Portland ESL Network Logo") %></a>
      <a href="/"><%= image_tag("header-title.jpg", alt: "Portland ESL Network Logo") %></a> -->
    </div>
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'Home', root_path, class: 'navbar-brand', 'data-no-turbolink' => true %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if current_admin %>
          <li><%= link_to 'Admin', admin_path %></li>
          <% end %>
          <li><%= link_to 'Class List', sites_path %></li>
          <li><%= link_to 'Volunteer', "/sites?volunteers_needed=true" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Students<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Learning Resources', "/links?type=learning" %></li>
              <li><%= link_to 'Real World Learning', real_world_path %></li>
              <li><a href="https://www.facebook.com/PortlandESL" target="_blank">Facebook Page</a></li>            
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Teachers<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Teaching Resources', "/links?type=teaching" %></li>
              <li><%= link_to 'Refugee Backgrounders', "/links?type=refugees" %></li>
              <li><a href="https://www.facebook.com/groups/PortlandESLNetwork" target="_blank">Facebook Discussion Group</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'About Portland ESL Network', about_path %></li>
              <li><a href="https://portlandesl.wixsite.com/wixsite/blog" target="_blank">Community News</a></li>
              <li><a href="http://www.pptpdx.org/pdxinterculture/" target="_blank">Intercultural Calendar</a></li>
              <li><%= link_to 'Volunteer with Us!', volunteer_path %></li>
              <li><a href="https://portlandesl.wixsite.com/wixsite/blog" target="_blank">COVID-19 Updates</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <main role="main">
        <%= yield %>
      </main>
    </div>
  </body>
</html>